# This is a basic workflow to help you get started with Actions

name: Blog posts on ReadMe
on:
  schedule:
    # Runs every day at 9am UTC
    - cron: '0 4 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Get RSS Feed
        uses: kohrongying/readme-the-rss@master
        with:
          feed_url: https://anuraj.dev/blog/feed.rss
          count: 10
      - name: Commit file changes
        run: |
            git config --global user.name 'anuraj'
            git config --global user.email 'anuraj.p@msn.com'
            git add .
            git diff --quiet --cached || git commit -m "Update README"    
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
